DEV: Adds RSpec tests
oblakeerickson/discourse-video pull request #15
Opened 2021-06-09 12:50 UTC by Ahmedgagan

@oblakeerickson

2021-06-09 12:53 UTC, Ahmedgagan commented on spec/components/guardian_spec.rb
> +      expect(guardian.can_upload_video?).to eq(true)
hey @oblakeerickson, can you take a look at this? Here the method we added using `add_to_class`(can_upload_video?) is not called and it directly returns `nil` I tried very hard to find a solution, but can't get the reason why this is happening

2021-06-09 21:42 UTC, oblakeerickson commented on spec/components/guardian_spec.rb
> +      expect(guardian.can_upload_video?).to eq(true)
Yep, I'll take a look.

2021-06-09 23:27 UTC, oblakeerickson requested changes
I added a code suggestion. The plugin needs to be enabled ;) Don't worry it took me a bit to realize this too.

2021-06-09 23:27 UTC, oblakeerickson commented on spec/components/guardian_spec.rb
> +
```suggestion
before do
  SiteSetting.discourse_video_enabled = true
end
```

2021-06-09 23:58 UTC, Ahmedgagan commented on spec/components/guardian_spec.rb
> +
Thanks a lot 😊 that was very silly one 🤦‍♂️ I wasted a day on this

2021-06-10 00:32 UTC, Ahmedgagan commented
@oblakeerickson Added a commit with the suggested change & some more RSpec tests.

2021-06-10 15:40 UTC, oblakeerickson approved these changes

2021-06-10 15:40 UTC, merged